/**
 * This file is auto-generated by scripts/generateRegistry.js
 * DO NOT EDIT MANUALLY.
 */

export interface Topic {
  name: string;
  descriptionPath: () => Promise<any>;
}

export interface Category {
  name: string;
  topics: Topic[]; 
}

export const docsRegistry: Category[] = [
  {
    name: "Getting Started",
    topics: [
      {
        name: "Installation",
        descriptionPath: () => import("@/app/docs/_content/Getting Started/Installation/description")
      }
    ]
  },
  {
    name: "Effects",
    topics: [
      {
        name: "SxPixelate",
        descriptionPath: () => import("@/app/docs/_content/Effects/SxPixelate/description")
      },
      {
        name: "SxASCII",
        descriptionPath: () => import("@/app/docs/_content/Effects/SxASCII/description")
      }
    ]
  }
];

export const flatDocIndex: string[] = [
  "Installation",
  "SxPixelate",
  "SxASCII"
];
