/**
 * This file is auto-generated by scripts/generateRegistry.js
 * DO NOT EDIT MANUALLY.
 */

export interface TabRender {
  name: string;
  componentPath: () => Promise<any>;
}

export interface TopicTab {
  name: string;
  renders: TabRender[];
}

export interface Topic {
  name: string;
  descriptionPath: () => Promise<any>;
  optionsPath?: () => Promise<any>;
  tabs?: TopicTab[];
}

export interface Category {
  name: string;
  topics: Topic[]; 
}

export const docsRegistry: Category[] = [
  {
    name: "Getting Started",
    topics: [
      {
        name: "Installation",
        descriptionPath: () => import("@/app/docs/_content/Getting Started/Installation/description")
      }
    ]
  },
  {
    name: "Effects",
    topics: [
      {
        name: "SxPixelate",
        descriptionPath: () => import("@/app/docs/_content/Effects/SxPixelate/description"),
        optionsPath: () => import("@/app/docs/_content/Effects/SxPixelate/options.json"),
        tabs: [
          {
            name: "Examples",
            renders: [
              {
                name: "Basic  Usage",
                componentPath: () => import("@/app/docs/_content/Effects/SxPixelate/examples/Basic Usage")
              }
            ]
          }
        ]
      },
      {
        name: "SxASCII",
        descriptionPath: () => import("@/app/docs/_content/Effects/SxASCII/description"),
        optionsPath: () => import("@/app/docs/_content/Effects/SxASCII/options.json"),
        tabs: [
          {
            name: "Examples",
            renders: [
              {
                name: "Example Basic",
                componentPath: () => import("@/app/docs/_content/Effects/SxASCII/examples/ExampleBasic")
              }
            ]
          }
        ]
      }
    ]
  }
];

export const flatDocIndex: string[] = [
  "Installation",
  "SxPixelate",
  "SxASCII"
];
