import type { Metadata } from "next";
import { JetBrains_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { MotionConfig } from "motion/react";
import { ThemeProvider } from "@/Providers/theme-provider";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
})

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MotionConfig transition={{bounce: 0}}>
      <html lang="en" className="h-screen" suppressHydrationWarning>
        <body
          className={`${quicksand.variable} ${jetBrainsMono.variable} antialiased h-full`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </MotionConfig>
  );
}
